# mocks the workflow diagram here: https://github.com/rapidsai/actions/actions/runs/4868448744
name: Nightly RAPIDS Pipeline Mock

on: push

concurrency:
  group: nightly-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true



# Build jobs should always run
# Test jobs should always run as long as their build job succeeds


jobs:
  get-run-info:
    runs-on: ubuntu-latest
    steps:
      - name: get-run-info
        run: echo "This is Job get-run-info"
  rmm-build:
    needs: get-run-info
    runs-on: ubuntu-latest
    steps:
      - name: rmm-build
        run: |
          echo "This job fails"
          exit 1
  rmm-tests:
    needs: [get-run-info, rmm-build]
    if: ${{ needs.rmm-build.result == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: rmm-tests
        run: echo "This is Job rmm-tests"
  cudf-build:
    needs: [get-run-info, rmm-build]
    runs-on: ubuntu-latest
    if: ${{ !cancelled() }}
    steps:
      - name: cudf-build
        run: echo "This is Job cudf-build"
  cudf-tests:
    needs: [get-run-info, cudf-build]
    if: ${{ needs.cudf-build.result == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: cudf-tests
        run: echo "This is Job cudf-tests"